name: myunila
description: "A new Flutter project for university information management."
publish_to: 'none' # Indicates this package is not meant to be published.

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8 # Latest version for Cupertino icons.
  provider: ^6.0.5 # State management for Flutter.
  http: ^1.2.2 # Updated HTTP package for API requests.
  shared_preferences: ^2.0.15 # For local storage needs.
  url_launcher: ^6.0.20 # To open URLs, such as for customization system.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0 # Lint rules to enforce clean code.
  
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Public-Sans
      fonts:
        - asset: assets/fonts/PublicSans-Thin.ttf
        - asset: assets/fonts/PublicSans-Bold.ttf
